GEMINI_API_KEY = "AIzaSyAnukquerlIIEq5W5HqMGj-2Srd8M-EC1Y"
MAX_TWEETS_PER_REQUEST = 5
CACHE_DURATION_HOURS = 1
ARTICLE_CACHE_PATH = "article_cache.json"
PROCESSED_ARTICLES_PATH = "processed_articles.json"
GEMINI_RESPONSES_PATH = "gemini_responses.json"